# Generated by Django 3.0.8 on 2021-04-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, unique=True, upload_to='path/to/img'),
        ),
    ]
