# Generated by Django 3.0.8 on 2021-03-12 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210309_2045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowRequest',
            new_name='FriendRequest',
        ),
    ]
