# Generated by Django 3.0.8 on 2021-04-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210315_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=None, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
